# Generated by Django 5.0.4 on 2024-04-13 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50, unique=True)),
                ('owner_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('sales_executive', models.CharField(max_length=50, null=True)),
                ('amount', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('duration', models.CharField(choices=[('seven_days', 'Seven Days'), ('one_month', 'One Month'), ('four_month', 'Four Month'), ('six_month', 'Six Month'), ('tweleve_month', 'Twelve Month'), ('twentyfour_month', 'Twenty-Four Month')], max_length=100)),
                ('website', models.URLField()),
                ('agreement', models.ImageField(blank=True, null=True, upload_to='agreements/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
