# Generated by Django 5.0.4 on 2024-04-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0004_alter_hotelusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelusers',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelusers',
            name='tax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelusers',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
