# Generated by Django 5.0.4 on 2024-04-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0006_alter_hotelusers_amount_alter_hotelusers_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelusers',
            name='unique_url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
