# Generated by Django 5.0.4 on 2024-04-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0002_alter_hotelusers_user'),
        ('hotel', '0002_alter_category_user_alter_menuitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_categories', to='admin_backend.hotelusers'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_menus', to='admin_backend.hotelusers'),
        ),
    ]
